# TEAM_NAMES = [
#   'Arizona Diamondbacks',
#   'Atlanta Braves',
#   'Baltimore Orioles',
#   'Boston Red Sox',
#   'Chicago White Sox',
#   'Chicago Cubs',
#   'Cincinnati Reds',
#   'Cleveland Indians',
#   'Colorado Rockies',
#   'Detroit Tigers',
#   'Houston Astros',
#   'Kansas City Royals',
#   'Los Angeles Angels',
#   'Los Angeles Dodgers',
#   'Miami Marlins',
#   'Milwaukee Brewers',
#   'Minnesota Twins',
#   'New York Yankees',
#   'New York Mets',
#   'Oakland Athletics',
#   'Philadelphia Phillies',
#   'Pittsburgh Pirates',
#   'San Diego Padres',
#   'San Francisco Giants',
#   'Seattle Mariners',
#   'St. Louis Cardinals',
#   'Tampa Bay Rays',
#   'Texas Rangers',
#   'Toronto Blue Jays',
#   'Washington Nationals',
# ]

TEAM_NAMES = {
  'Arizona Diamondbacks' : 'ARI',
  'Atlanta Braves': 'ATL',
  'Baltimore Orioles': 'BAL',
  'Boston Red Sox': 'BOS',
  'Chicago White Sox': 'CWS',
  'Chicago Cubs': 'CHC',
  'Cincinnati Reds': 'CIN',
  'Cleveland Indians': 'CLE',
  'Colorado Rockies': 'COL',
  'Detroit Tigers': 'DET',
  'Houston Astros': 'HOU',
  'Kansas City Royals': 'KC',
  'Los Angeles Angels': 'LAA',
  'Los Angeles Dodgers': 'LAD',
  'Miami Marlins': 'MIA',
  'Milwaukee Brewers': 'MIL',
  'Minnesota Twins': 'MIN',
  'New York Yankees': 'NYY',
  'New York Mets': 'NYM',
  'Oakland Athletics': 'OAK',
  'Philadelphia Phillies': 'PHI',
  'Pittsburgh Pirates': 'PIT',
  'San Diego Padres': 'SD',
  'San Francisco Giants': 'SF',
  'Seattle Mariners': 'SEA',
  'St. Louis Cardinals': 'STL',
  'Tampa Bay Rays': 'TB',
  'Texas Rangers': 'TEX',
  'Toronto Blue Jays': 'TOR',
  'Washington Nationals': 'WAS'
}
CHROMEDRIVER_PATH = 'chromedriver.exe'